#before_install:
# - sudo apt-get update -qq
# - sudo apt-get upgrade -qq
# - sudo apt-get install python python-pip
install:
 - pip install requests
 - git clone git://github.com/aklsglaliyu/travis scripts
script:
 - python scripts/build.py
